// <auto-generated />
using System;
using AareonTechnicalTest;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AareonTechnicalTest.Migrations
{
	[DbContext(typeof(ApplicationContext))]
	[Migration("20220421152423_AddedAutoHistory")]
	partial class AddedAutoHistory
	{
		/// <summary>EF built target model.</summary>
		/// <param name="modelBuilder">Model builder.</param>
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

			modelBuilder.Entity("AareonTechnicalTest.Models.Person", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<string>("Forename")
						.HasColumnType("TEXT");

					b.Property<bool>("IsAdmin")
						.HasColumnType("INTEGER");

					b.Property<string>("Surname")
						.HasColumnType("TEXT");

					b.HasKey("Id");

					b.ToTable("Persons");
				});

			modelBuilder.Entity("AareonTechnicalTest.Models.Ticket", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<string>("Content")
						.HasColumnType("TEXT");

					b.Property<int>("PersonId")
						.HasColumnType("INTEGER");

					b.HasKey("Id");

					b.HasIndex("PersonId");

					b.ToTable("Tickets");
				});

			modelBuilder.Entity("AareonTechnicalTest.Models.TicketNote", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<string>("Note")
						.IsRequired()
						.HasMaxLength(254)
						.HasColumnType("TEXT");

					b.Property<int>("PersonId")
						.HasColumnType("INTEGER");

					b.Property<int>("TicketId")
						.HasColumnType("INTEGER");

					b.HasKey("Id");

					b.HasIndex("PersonId");

					b.HasIndex("TicketId");

					b.ToTable("TicketNotes");
				});

			modelBuilder.Entity("Microsoft.EntityFrameworkCore.AutoHistory", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<string>("Changed")
						.HasColumnType("TEXT");

					b.Property<DateTime>("Created")
						.HasColumnType("TEXT");

					b.Property<int>("Kind")
						.HasColumnType("INTEGER");

					b.Property<string>("RowId")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("TEXT");

					b.Property<string>("TableName")
						.IsRequired()
						.HasMaxLength(128)
						.HasColumnType("TEXT");

					b.HasKey("Id");

					b.ToTable("AutoHistory");
				});

			modelBuilder.Entity("AareonTechnicalTest.Models.Ticket", b =>
				{
					b.HasOne("AareonTechnicalTest.Models.Person", null)
						.WithMany("Tickets")
						.HasForeignKey("PersonId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("AareonTechnicalTest.Models.TicketNote", b =>
				{
					b.HasOne("AareonTechnicalTest.Models.Person", null)
						.WithMany("TicketNotes")
						.HasForeignKey("PersonId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("AareonTechnicalTest.Models.Ticket", null)
						.WithMany("TicketNotes")
						.HasForeignKey("TicketId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("AareonTechnicalTest.Models.Person", b =>
				{
					b.Navigation("TicketNotes");

					b.Navigation("Tickets");
				});

			modelBuilder.Entity("AareonTechnicalTest.Models.Ticket", b =>
				{
					b.Navigation("TicketNotes");
				});
#pragma warning restore 612, 618
		}
	}
}
